remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Machine Learning to 1D Astronomical Dataset
description: Harvesting spectroscopic and time series data with machine learning and artificial intelligence. 
