remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Machine Learning to 1D Astronomical Dataset
description: Practical details of the RAS specialist discussion meeting on Friday 10 MARCH 2023. 
