remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Machine Learning to one-dimensional Astronomical Dataset
description: Practical details of the RAS specialist discussion meeting on Friday 10 MARCH 2023. 
